default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db
  port: 3306

development:
  <<: *default
  database: cf_app_development
  host: db
  username: root
  password: password

test:
  <<: *default
  database: cf_app_test

production:
  <<: *default
  database: cf_app_production
