default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  port: <%= ENV['DB_PORT'] || 3306 %>

development:
  <<: *default
  database: cf_app_development
  host: db
  username: root
  password: password

test:
  <<: *default
  database: cf_app_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
